### ISSUE TITLE
this mod is too sigma

### ISSUE THREAD

**Issue by jdjdnxb** [NoWare-Development/mc-purity#1]
this mod is too sigmathis mod is too sigmathis mod is too sigmathis mod is too sigmathis mod is too sigmathis mod is too sigmathis mod is too sigmathis mod is too sigma

**Comment by Nyvyme** [comment]
no u

**Comment by jdjdnxb** [comment]
> no u

more sigma

**Comment by senhas-rgb** [comment]
bruh
